apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: httpd:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080

