apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: default  # Optional: specify the namespace if not using the default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJhZGl0eWFiMDEiLAogICAgICAicGFzc3dvcmQiOiAiRG9ja2VyMTIzIyIsCiAgICAgICJlbWFpbCI6ICJhZGl0eWFiaHV0bWFyZUBnbWFpbC5jb20iCiAgICB9CiAgfSwKICAiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKICAiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCiAgInBsdWdpbnMiOiB7CiAgICAiLXgtY2xpLWhpbnRzIjogewogICAgICAiZW5hYmxlZCI6ICJ0cnVlIgogICAgfSwKICAgICJkZWJ1ZyI6IHsKICAgICAgImhvb2tzIjogImV4ZWMiCiAgICB9LAogICAgInNjb3V0IjogewogICAgICAiaG9va3MiOiAicHVsbCxidWlsZHggYnVpbGQiCiAgICB9CiAgfSwKICAiZmVhdHVyZXMiOiB7CiAgICAiaG9va3MiOiAidHJ1ZSIKICB9Cn0KCg==
