project: default
source:
  repoURL: 'https://github.com/theadityab/argo-testing.git'
  path: argo-helm
  targetRevision: HEAD
  helm:
    valueFiles:
      - test-values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: myapp
