apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-develop
  namespace: argocd
spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  project: bu-test
  source:
    helm:
      valueFiles:
      - values-dev.yaml
    path: 
    repoURL: https://github.com/theadityab/argo-testing.git
    targetRevision: release-1.1
  syncPolicy:
    automated: null
