apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-dev
  namespace: argocd
spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  project: bu-test
  source:
    helm:
      valueFiles:
      - values-dev.yaml
    path: argo-helm
    repoURL: https://github.com/theadityab/argo-testing.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
