apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bu-test
  namespace: argocd
spec:
  description: Testing Project for an application 
  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

