# templates/argo-application.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  project: {{ .Values.project }}

  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.path }}
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: replicaCount
        value: "{{ .Values.replicaCount }}"
      - name: image.tag
        value: "{{ .Values.image.tag }}"
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: false
      prune: false


  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: false
      prune: false

