# values.yaml

name: myapp-argo-application
namespace: nginx-adi
project: default
repoURL: https://gitlab.com/nanuchi/argocd-app-config.git
path: dev
destination:
  server: https://kubernetes.default.svc
  namespace: myapp


